### ISSUE TITLE
ModuleNotFoundError: No module named 'mdtraj'

### ISSUE THREAD

**Issue by elwait** [bdw2292/AMOEBAAnnihilator#3]
I attempted to use AMOEBAAnnihilator to get complex of MELK and IN17 from docking structure, MELK pdb, and IN17 xyz and key  and I got the following error message:

nohup.out
```
Traceback (most recent call last):
  File "/home/eew947/AMOEBAAnnihilator/AMOEBAAnnihilatorModules/amoebaannihilator.py", line 3, in <module>
    import annihilation as ann
  File "/home/eew947/AMOEBAAnnihilator/AMOEBAAnnihilatorModules/annihilation.py", line 8, in <module>
    import minimization as mini
  File "/home/eew947/AMOEBAAnnihilator/AMOEBAAnnihilatorModules/minimization.py", line 6, in <module>
    import restraints as res
  File "/home/eew947/AMOEBAAnnihilator/AMOEBAAnnihilatorModules/restraints.py", line 4, in <module>
    import mdtraj as md
ModuleNotFoundError: No module named 'mdtraj'
```

My files are located here:
`/home/eew947/MELK_IN17_rep/AA_input`
`/home/eew947/AMOEBAAnnihilator/`

This is my AMOEBA.ini:
```
uncomplexedproteinpdbname=uncomplexed.pdb
complexedproteinpdbname=melk_in17.pdb
complexation
outputpath=/home/eew947/MELK_IN17_rep/AA_input/complexation
keyfilename=melk_in17.key
ligandxyzfilename=in17.xyz
keyfilename=in17.key
prmfilepath=/home/bdw2292/currentstable/ParameterFiles/amoebabio18.prm
```

This is the bashrc I sourced, according to @bdw2292 's instructions (use poltype env for a quick start because it has openbabel). I am on node144.

/home/eew947/.aa.bashrc
```
#!/usr/bin/bash -f

#Python & openbabel
export PATH="/home/eew947/miniconda3/bin/:$PATH"
export PATH="/home/eew947/miniconda3/condabin/conda:$PATH"

#conda activate poltype env
conda activate poltype
alias run_aa="nohup python /home/eew947/AMOEBAAnnihilator/AMOEBAAnnihilatorModules/amoebaannihilator.py &"

#Tinker
export PATH=/home/bdw2292/LatestTinker/source/:$PATH
```

**Comment by bdw2292** [comment]
Fixed in readme_install
